### ISSUE TITLE
TestThreadContainer is not a parent for Scenario Container anymore

### ISSUE THREAD

**Issue by gmrozikmedius** [reqnroll/Reqnroll#101]
### Reqnroll Version

1.0.1

### Which test runner are you using?

NUnit

### Test Runner Version Number

1.0.1

### .NET Implementation

.NET 8.0

### Test Execution Method

ReSharper Test Runner

### Content of reqnroll.json configuration file

empty

### Issue Description

The instance of the class registered in TestThreadContainer is not available in the ScenarioContainer.
It worked like a charm in Specflow 3.9.74.

Use case:
- we have some configuration of tests that needs to be loaded from files
- it takes some time so we want to do this once before all tests
- we did it in the BeforeTestRun hook and the instance of configuration was registered to TestThreadContext.TestThreadContainer using RegisterInstance method
- then we accessed it in all Scenarios by injecting it through the constructor

### Steps to Reproduce

```
using Reqnroll;

namespace reqnroll_test;

[Binding]
public class Hooks
{
    [BeforeTestRun]
    public static void BeforeTest(TestThreadContext testThreadContext)
    {
        var configuration = LoadConfigurationItTakesFewMinutes();

        testThreadContext.TestThreadContainer.RegisterInstanceAs(configuration);
    }

    private static Configuration LoadConfigurationItTakesFewMinutes()
    {
        return new Configuration()
        {
            Property = "test"
        };
    }
}

[Binding]
public class Steps
{
    private readonly Configuration _configuration;

    public Steps(Configuration configuration)
    {
        _configuration = configuration;
    }

    [Given(@"test using dependency registered in test thread container")]
    public void GivenTestUsingDependencyRegisteredInTestThreadContainer()
    {
        Assert.That(_configuration.Property, Is.EqualTo("test"));
    }
}

public class Configuration
{
    public string? Property { get; set; }
}
```

```
Feature: Test
    
    Scenario: Scenario1
        Given test using dependency registered in test thread container 
```

This test fails. The same test in Specflow 3.9.74 is green.

**UPDATE:**
I checked that this test fails also in Specflow 3.10.2-beta

**UPDATE 2:**
I found that one difference between Specflow 3.9.74 and 3.10.2-beta is that they introduced async/await all the time. Maybe this is the reason why Test**Thread**Container changed the behavior?

**Comment by ajeckmans** [comment]
You are running into a change made here: #59  and discussed here: #88

**Comment by ajeckmans** [comment]
Basically there was a change made in Specflow v4 which rolled over to Reqnroll, which slightly changes how the tests are invoked. In runners like Nunit that entirely broke this part of resolving dependencies (or at least made it inconsistent), so a change was merged to make these specific scenario's work again. Unfortunately other changes were merged as well, which means that we now have the choice of waiting it out, or making a patch. For now @gasparnagy choose to wait for the other changes to be made as well, before releasing a v2.0.0

**Comment by gmrozikmedius** [comment]
Ok, thanks. I analyzed #59 and #88 threads, I found a local workaround so I will try to apply it. And I am waiting for version v2.0.0 :)
