### ISSUE TITLE
Contributing Page link to Discord server broken (403)

### ISSUE THREAD

**Issue by clrudolphi** [reqnroll/Reqnroll#14]
### Related Documentation Page

Contributing.md

### Type of the problem

Broken link or display

### Problem Description

At the bottom of the Contributing.md page is a link is supposed to go to Discord. It points to https://go.reqnroll.net/join-contributing-on-discord which results in a 403 (Forbidden)

**Comment by gasparnagy** [comment]
#10 fixed it thx.

**Comment by gasparnagy** [comment]
The contribution guide needs to be reviewed fully.

I don't use Discord, so one option would be to just guide users to the GitHub discussion board or slack (we could use one of the channels of the Cucumber slack). But if there is enough interest in using Discord, I can also use it. Just don't have the energy to learn how to setup & operate a Discord server.

@SabotageAndi do you still use Discord actively?

**Comment by SabotageAndi** [comment]
The original idea for using Discord at SpecFlow was, that we have a communication channel for contributors that is more real-time than a GitHub issue.

It was never for end users, as Discord is not indexed by Search Engines. All shared knowledge benefits only the person who asks and not someone else later.

If you @gasparnagy don't use Discord, I wouldn't create now a Discord server. The people want to reach you.

I use Discord private but for other things than SpecFlow.

**Comment by gasparnagy** [comment]
Ok. Let's be pragmatic. I created a dedicated [Contributor Q&A](https://github.com/orgs/reqnroll/discussions/categories/contributor-q-a) discussion group and replaced the Discord link to that.

We can rewise this strategy later of course.
