### ISSUE TITLE
Unable to install Nuget Package "Reqnroll.SpecFlowCompatibility.Actions.Selenium"

### ISSUE THREAD

**Issue by elysionconsulting** [reqnroll/Reqnroll#176]
### Reqnroll Version

2.0.2

### Which test runner are you using?

MSTest

### Test Runner Version Number

4.0.1

### .NET Implementation

.NET 8.0

### Test Execution Method

Visual Studio Test Explorer

### Issue Description

Trying to install package "Reqnroll.SpecFlowCompatibility.Actions.Selenium" but dependencies are wrong. So i always get error : 

Package restore failed. Rolling back package changes for 'ATR.AutomatedTests.Extranet'.
Unable to find package Reqnroll.Actions.Configuration. No packages exist with this id in source(s): ForemFeed, local-package, Microsoft Visual Studio Offline Packages, nuget.org

Reqnroll.Actions.Configuration ≥ 0.2.2
but this package doesn't exists, it should be "Reqnroll.SpecFlowCompatibility.Actions.Configuration" no ?

### Steps to Reproduce

Just install package "Reqnroll.SpecFlowCompatibility.Actions.Selenium"

**Comment by gasparnagy** [comment]
Thank you @dominik-niebuhr for the fix!
I will release the fix within a few days.

**Comment by SnoopyLove** [comment]
This issue is observed when I install Reqnroll.SpecFlowCompatibility.Actions.WindowsAppDriver. 
Gives me the following error message:
Unable to find package Reqnroll.Actions.Appium. No packages exist with this id in source(s)

**Comment by 304NotModified** [comment]
@SnoopyLove  please create a new issue, thanks
