### ISSUE TITLE
Why is there a difference between StepArgumentTransformation and IValueRetrievers

### ISSUE THREAD

**Issue by JelleHissink** [reqnroll/Reqnroll#178]
### Type of the problem

Incorrect information

### Problem Description

When already having a IValueRetriever, why do I need to also support a StepArgumentTransformation in order to convert the arguments, could the last step in this list https://docs.reqnroll.net/latest/automation/step-argument-conversions.html#standard-conversion not also fall back to the value retrievers? Or have the ValueRetrievers support for ChangeType by default.

It feels a bit like ValueRetrievers and StepArgumentTransformation transformations try to achieve the same goal, but are implemented totally differently.

**Comment by gasparnagy** [comment]
Yes, you are right. Currently these are two completely separate infrastructure.

We have started the planning for merging these in https://github.com/orgs/reqnroll/discussions/137. In that discussion you can also find a workaround to avoid duplication.

I close this issue, let's continue the planning in the linked discussion topic.
