### ISSUE TITLE
Using Autofac plugin Reqnroll.FeatureContext and [BeforeFeature]/[AfterFeature] attributes not working properly

### ISSUE THREAD

**Issue by RicardoLans** [reqnroll/Reqnroll#203]
### Reqnroll Version

2.0.3

### Which test runner are you using?

NUnit

### Test Runner Version Number

4.0.1

### .NET Implementation

.NET 8.0

### Test Execution Method

Visual Studio Test Explorer

### Issue Description

When following the steps to reproduce and placing breakpoints in the static methods I found 2 strange things:
- the AfterFeature attribute is not working, the static method where attribute is on is not called at all
- the FeatureContext in the static method of the BeforeFeature attribute is not registered in autofac

Before/After Scenario attributes/static methods are working properly and also the ScenarioContext is resolved.

### Steps to Reproduce

Using [this small and handy repo](https://github.com/q42jaap/MyRepro.Reqnroll.Autofac)

Edit the SetupHook.cs -> replace class with below (for now I used workaround in the Before/After TestRun)

```csharp
public class SetupHook
{
    [BeforeTestRun]
    public static void BeforeTestRun(IContainer container)
    {
        IMyImpl myImpl = container.Resolve<IMyImpl>();
    }

    [BeforeFeature]
    public static void BeforeFeature(FeatureContext featureContext, IMyImpl myImpl)
    {
    }

    [BeforeScenario]
    public static void BeforeScenario(ScenarioContext scenarioContext, IMyImpl myImpl)
    {
    }

    [AfterScenario]
    public static void AfterScenario(ScenarioContext scenarioContext, IMyImpl myImpl)
    {
    }

    [AfterFeature]
    public static void AfterFeature(FeatureContext featureContext, IMyImpl myImpl)
    {
    }

    [AfterTestRun]
    public static void AfterTestRun(IContainer container)
    {
        IMyImpl myImpl = container.Resolve<IMyImpl>();
    }
}
```
Run the test from Visual Studio Test Explorer

### Link to Repro Project

https://github.com/q42jaap/MyRepro.Reqnroll.Autofac

**Comment by RicardoLans** [comment]
Well, based on the ongoing discussion I can understand if this Issue might not be resolved.

In the meantime I will try to find a workaround for my project where we have to restore a database (or reset testdata) per feature file instead of per scenario.

**Comment by gasparnagy** [comment]
I close this issue for now to keep out tracking clear, but once the feature-hooks discussion moves on we can come back to this.
