### ISSUE TITLE
Features fail to build when using project references

### ISSUE THREAD

**Issue by paulio** [reqnroll/Reqnroll#211]
### Reqnroll Version

2.0.3

### Which test runner are you using?

MSTest

### Test Runner Version Number

?

### .NET Implementation

.NET 8.0

### Test Execution Method

Visual Studio Test Explorer

### Content of reqnroll.json configuration file

```
{
    "$schema": "https://schemas.reqnroll.net/reqnroll-config-latest.json",
    
    "bindingAssemblies": [
    ]
}

```

### Issue Description

I'm trying to use the latest build of ReqNRoll using project references and the code-behind code generation doesn't appear to be working

### Steps to Reproduce

1. I've pulled down the latest main of Reqnroll. 
2. I've added a a new Reqnroll NUnit Project to the solution
3. Built the project and the sample Calculator.feature has it's code-behind correctly generated
4. I've removed the (DLL) reference ReqnRoll.NUnit (2.0.2) and replaced it with Project References to ReqnRoll and ReqnRoll.Tools.MsBuild
5. I've repeated step (3) but the code-behind isn't generated. I've tried clearing/rebuilding but nothing occurs. Do I need to add a msbuild references or ? 
```
Build started at 09:19...
1>------ Build started: Project: ReqnrollProjectTestClient, Configuration: Debug Any CPU ------
1>ReqnrollProjectTestClient -> D:\Repros\Reqnroll\ReqnrollProjectTestClient\bin\Debug\net8.0\ReqnrollProjectTestClient.dll
========== Build: 1 succeeded, 0 failed, 5 up-to-date, 0 skipped ==========
========== Build completed at 09:19 and took 01.576 seconds ==========

```

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.10.0" />
    <PackageReference Include="nunit" Version="3.14.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.5.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Drivers\" />
    <Folder Include="Support\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Reqnroll.Tools.MsBuild.Generation\Reqnroll.Tools.MsBuild.Generation.csproj" />
    <ProjectReference Include="..\Reqnroll\Reqnroll.csproj" />
  </ItemGroup>
</Project>

```

**Comment by gasparnagy** [comment]
Cloning the Reqnroll project and start your own test project based on the own Reqnroll samples is not the intended way for setting up a new Reqnroll project. Our own way of using Reqnroll is special because we cannot use NuGet packages internally - so this is not the way to go.

For setting up a Reqnroll project, please use the guide described in the documentation: https://docs.reqnroll.net/latest/installation/setup-project.html 

I close this issue now, but please feel free to reopen if you get into troubles based on the setup guide as well.

**Comment by paulio** [comment]
Hi, sorry, I want to create a new plugin, not setup an existing project.

**Comment by gasparnagy** [comment]
@paulio For making a new plugin, please follow the guide here: https://docs.reqnroll.net/latest/extend/plugins.html

You do not need project refs for that either.
