### ISSUE TITLE
Error when installing the Reqnroll template via command line

### ISSUE THREAD

**Issue by tulavalle** [reqnroll/Reqnroll#22]
### Reqnroll Version

1.0.0

### Which test runner are you using?

xUnit

### Test Runner Version Number

--

### .NET Implementation

.NET 8.0

### Test Execution Method

Visual Studio Test Explorer

### Content of reqnroll.json configuration file

It did not reach the .NET version configuration stage, nor the test executor, nor creating the reqnrollfile. were filled in as it is a mandatory field

### Issue Description

Error when installing the Reqnroll template via command line

### Steps to Reproduce

Hey! I was able to successfully create a project with Reqnroll template via Visual Studio, but when doing the same via vs code, via the command line, when installing Reqnroll template with the command 'dotnet new install Reqnroll.Templates.DotNet', I got an error stating that it was already the template existed, making reference to Specflow. I uninstalled the Specflow template, restarted the machine and tried the installation again, getting the following error:

image

and, as a result, the template was not installed, generating an error when executing the command ´dotnet new reqnroll-project´:
image

dotnet new list:

image

Are there any other steps I need to do or could it be an error in the template script?

**Comment by tulavalle** [comment]
> ### Reqnroll Version
> 1.0.0
> 
> ### Which test runner are you using?
> xUnit
> 
> ### Test Runner Version Number
> --
> 
> ### .NET Implementation
> .NET 8.0
> 
> ### Test Execution Method
> Visual Studio Test Explorer
> 
> ### Content of reqnroll.json configuration file
> It did not reach the .NET version configuration stage, nor the test executor, nor creating the reqnrollfile. were filled in as it is a mandatory field
> 
> ### Issue Description
> Error when installing the Reqnroll template via command line
> 
> ### Steps to Reproduce
> Hey! I was able to successfully create a project with Reqnroll template via Visual Studio, but when doing the same via vs code, via the command line, when installing Reqnroll template with the command 'dotnet new install Reqnroll.Templates.DotNet', I got an error stating that it was already the template existed, making reference to Specflow. I uninstalled the Specflow template, restarted the machine and tried the installation again, getting the following error:
> 
> image
> 
> and, as a result, the template was not installed, generating an error when executing the command ´dotnet new reqnroll-project´: image
> 
> dotnet new list:
> 
> image
> 
> Are there any other steps I need to do or could it be an error in the template script?
> 
> ### Link to Repro Project
> _No response_

Sorry, there was an error sending the images, they are in order below:
![image](https://github.com/reqnroll/Reqnroll/assets/108248997/acf06c23-4ccf-477c-a39d-3a62d86d3376)

![image](https://github.com/reqnroll/Reqnroll/assets/108248997/50962c9c-3a5b-4a87-bd88-b9f260fff43a)
![image](https://github.com/reqnroll/Reqnroll/assets/108248997/10967d83-d189-480f-87cb-da970785585d)

**Comment by johnboygit** [comment]
I also got the same error mentioned here.

**Comment by gasparnagy** [comment]
This seems to be related to https://github.com/dotnet/msbuild/issues/3468
The `WriteLinesToFile` task replaced the `\"` seqence in JSON to `/"` on Linux, were we produce the build.

**Comment by gasparnagy** [comment]
Seems to be working. Will be released soon.
