### ISSUE TITLE
How to get HTML or JSON report from reqnroll just like Cucumber.io

### ISSUE THREAD

**Issue by ShanmukhaGajula** [reqnroll/Reqnroll#223]
### Type of the problem

Missing information

### Problem Description

Hello,
I have started exploring Reqnroll and unable to find how to get HTML or JSON report from reqnroll just like cucumber.io. Could you please provide that information

**Comment by ShanmukhaGajula** [comment]
I even tried using SpecFlow+ LivingDoc’s even this is not producing the results in json. below is the sample json

`{"Nodes":[],"ExecutionTime":"2024-07-24T15:01:53.3406789Z","GenerationTime":"0001-01-01T00:00:00","PluginUserSpecFlowId":"1943d37b-df11-4806-b32a-189027549930","CLIUserSpecFlowId":null,"ExecutionResults":[{"ContextType":"Scenario","FeatureFolderPath":"Features","FeatureTitle":"Bid Creation","ScenarioTitle":"MNC Bid creation","ScenarioArguments":[],"Status":"UndefinedStep","StepResults":[{"Duration":null,"Status":"UndefinedStep","Error":null,"Outputs":null},{"Duration":null,"Status":"UndefinedStep","Error":null,"Outputs":null}],"Outputs":null},{"ContextType":"Scenario","FeatureFolderPath":"Features","FeatureTitle":"Feature1","ScenarioTitle":"[scenario name]","ScenarioArguments":[],"Status":"UndefinedStep","StepResults":[{"Duration":null,"Status":"UndefinedStep","Error":null,"Outputs":null},{"Duration":null,"Status":"UndefinedStep","Error":null,"Outputs":null},{"Duration":null,"Status":"UndefinedStep","Error":null,"Outputs":null}],"Outputs":null}],"StepReports":null}`

**Comment by Drew99Kt** [comment]
have you tried --logger? 
https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-test

not sure if this is what you were asking for but might be something ?

**Comment by ShanmukhaGajula** [comment]
I am kind of looking for similar thing
https://cucumber.io/docs/cucumber/reporting/?lang=java

**Comment by gasparnagy** [comment]
We don't have this yet, but @clrudolphi is working on it currently. Here is the discussion that tracks this feature: https://github.com/orgs/reqnroll/discussions/202
