### ISSUE TITLE
forward slash "/" causes reqNRoll to fail to find step method

### ISSUE THREAD

**Issue by Drew99Kt** [reqnroll/Reqnroll#228]
### Reqnroll Version

"Reqnroll" Version="2.0.3" 

### Which test runner are you using?

xUnit

### Test Runner Version Number

"Reqnroll.xUnit" Version="2.0.3" 

### .NET Implementation

.NET 8.0

### Test Execution Method

Visual Studio Test Explorer

### Issue Description

forward slash "/" causes reqNRoll to fail to find step method

### Steps to Reproduce

1. create a feature file
2. create a single test. 
  - Scenario: test
    Given a
    Given a/c
    Given c/c
3. implement the 3 step methods into a binding class.
4. build project

you can see "Given a" is found but Give a/c and c/c are not found. Running test results in test "No matching step definition found for one or more steps."

### picture 
![image](https://github.com/user-attachments/assets/317fe0ee-4277-48cc-9910-d6bd903ddc65)

**Comment by Drew99Kt** [comment]
later i will try to add example project.

**Comment by clrudolphi** [comment]
Please show your step definitions. The slash character is a special character. It is used to indicate alternatives ([see](https://docs.reqnroll.net/latest/automation/cucumber-expressions.html#optionals-alternatives)

**Comment by clrudolphi** [comment]
> > Please show your step definitions. The slash character is a special character. It is used to indicate alternatives ([see](https://docs.reqnroll.net/latest/automation/cucumber-expressions.html#optionals-alternatives))
> 
> ![image](https://github.com/user-attachments/assets/0f933b23-7086-4f1e-9880-ee1b0cf7c5d0)
> ![image](https://github.com/user-attachments/assets/6fa6068f-b177-4c5d-8bd1-16b746e51387)
> 
> ok some how this was not working correctly on specflow. maybe i had a old version installed. will close this bug.  Thanks. 
> 

The difference in behavior between SpecFlow and Reqnroll is because in the Step definition syntax Reqnroll uses Cucumber expressions by default (which uses the slash to indicate alternatives) while SpecFlow used Regex. You can always force to use regular expression by specifying the regex start/end markers (^/$).
