### ISSUE TITLE
MsTest out not attaching all the results file to the report, when running multiple feature tests

### ISSUE THREAD

**Issue by potnoddle** [reqnroll/Reqnroll#236]
### Reqnroll Version

latest

### Which test runner are you using?

MSTest

### Test Runner Version Number

3.5.2

### .NET Implementation

.NET 8.0

### Test Execution Method

Command line – PLEASE SPECIFY THE FULL COMMAND LINE

### Content of reqnroll.json configuration file

dotnet test --logger "trx;LogFileName=TestResults.trx"

### Issue Description

Using ReqnRoll with Playwright I wish to attach screenshots and video to a report. However, when .trx file doesn't record all the files attached with the AddResultFile method. Only the first one appears?

I fixed images by I injecting the testContext for each hook and to fix videos I need to add the video for each Scenario, so I a senior has multiple Scenario it gets multiple links to the video!

There looks like two issues, BeforeFeature is executed only once for multiple features and AfterFeature doesn't accept video!

### Steps to Reproduce

Create project

add multiple steps

create a hooks file with [Before] and [After] attributes

use _testContext.AddResultFile(path);

**Comment by potnoddle** [comment]
You can create files and pass the TestContext to these methods and the issue seems to be the files are deleted and copy copies to the final folder.

Do you know how I can tell what the final output folder will be, ie the one without the Deploy prefix.

**Comment by gasparnagy** [comment]
> You can create files and pass the TestContext to these methods and the issue seems to be the files are deleted and copy copies to the final folder.

I think I am lost now. If this works than what your real problem is? Could you please include some code snippet so that I can better understand?

> Do you know how I can tell what the final output folder will be, ie the one without the Deploy prefix.

This is provided by the test runner, maybe you can configure it with a [`.runsettings` file](https://learn.microsoft.com/en-us/visualstudio/test/configure-unit-tests-by-using-a-dot-runsettings-file?view=vs-2022), but I don't know.

**Comment by gasparnagy** [comment]
@potnoddle Do you have any feedback on this?

**Comment by gasparnagy** [comment]
Closing this for now, if you have any feedback, please reopen.
