### ISSUE TITLE
Reqnroll.CustomPlugin has System.CodeDom version mismatch 

### ISSUE THREAD

**Issue by UL-ChrisGlew** [reqnroll/Reqnroll#244]
### Reqnroll Version

2.1.0

### Which test runner are you using?

NUnit

### Test Runner Version Number

N/A

### .NET Implementation

.NET 8.0

### Test Execution Method

Visual Studio Test Explorer

### Content of reqnroll.json configuration file

{}

### Issue Description

Having problems with System.CodeDom in the Reqnroll.CustomPlugin NuGet package.

Looking at the project references tree, the dependent project **Reqnroll.Generator** requires version 8.0.0:

![image](https://github.com/user-attachments/assets/e0396ab6-1f03-440b-91e7-696b7dbbfa4d)

However, the .nuspec file for **Reqnroll.CustomPlugin** specifially calls for version 4.4.0:

![image](https://github.com/user-attachments/assets/8c4ca7ee-dacd-40d5-8285-663d0a5888a7)

It appears that this mis-match is causing issues when attempting to build projects that reference the **Reqnroll.CustomPlugin** package:

![image](https://github.com/user-attachments/assets/e94d5516-5c4b-4620-8717-3467805d1ab6)

### Steps to Reproduce

(See above)

**Comment by user93485938459** [comment]
Anyone else still having issues with this? Same problem with 2.1.1

**Comment by UL-ChrisGlew** [comment]
I'm not seeing this issue since v2.1.1 was released. Did you try rebuilding the project a few times once updated? I found that seemed to flush the issue through for me.

**Comment by user93485938459** [comment]
I tried a few times, ultimately the package that was giving me trouble was an external retry plugin. Ended up switching from https://github.com/chrisbillson/NUnitRetry.ReqnrollPlugin to https://www.nuget.org/packages/databinding.Reqnroll.NUnit.Retry/5.8.8#show-readme-container and problem is solved
