### ISSUE TITLE
Dotnet publish task failed in the Azure Devops Pipeline

### ISSUE THREAD

**Issue by darren-zdc** [reqnroll/Reqnroll#251]
### Reqnroll Version

2.1.0

### Which test runner are you using?

xUnit

### Test Runner Version Number

2.0

### .NET Implementation

.NET 8.0

### Test Execution Method

Visual Studio Test Explorer

### Content of reqnroll.json configuration file

n/a

### Issue Description

We used to build our Xunit project with version 2.0.3. And it works perfectly. However, when we updated to version 2.1.0, our Azure pipeline task failed with a strange error. And we couldn't reproduce it locally. 

I copied the entire task log to here. I wonder if someone could give us some hints here. I really like Reqnroll, and really want to continue using it. 

The only changes from the generated feature cs file after we updated the package version is the following. 

From
```
 public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(null, global::Reqnroll.xUnit.ReqnrollPlugin.XUnitParallelWorkerTracker.Instance.GetWorkerId());
            global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Job", "Job API Operations", "\tAs a user\r\n\tI want to perform CRUD operations related to Job\r\n\tSo I can do certa" +
                    "in actions", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
            await testRunner.OnFeatureStartAsync(featureInfo);
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            string testWorkerId = testRunner.TestWorkerId;
            await testRunner.OnFeatureEndAsync();
            testRunner = null;
            global::Reqnroll.xUnit.ReqnrollPlugin.XUnitParallelWorkerTracker.Instance.ReleaseWorker(testWorkerId);
        }
        
``` 
To
```
public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly();
            global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Job", "Job API Operations", "\tAs a user\r\n\tI want to perform CRUD operations related to Job\r\n\tSo I can do certa" +
                    "in actions", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
            await testRunner.OnFeatureStartAsync(featureInfo);
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await testRunner.OnFeatureEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
            testRunner = null;
        }
``` 

Log from Azure publish task. 
```
Starting: dotnet publish Datahunter.Tests
==============================================================================
Task         : .NET Core
Description  : Build, test, package, or publish a dotnet application, or run a custom dotnet command
Version      : 2.242.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/dotnet-core-cli
==============================================================================
Info: .NET Core SDK/runtime 2.2 and 3.0 are now End of Life(EOL) and have been removed from all hosted agents. If you're using these SDK/runtimes on hosted agents, kindly upgrade to newer versions which are not EOL, or else use UseDotNet task to install the required version.
/data/agent/_work/_tool/dotnet/dotnet publish /data/agent/_work/95/s/DataHunter-Main/tests/Datahunter.Tests/Datahunter.Tests.csproj -o DataHunter-Main/tests/Datahunter.Tests/out/Datahunter.Tests
  Determining projects to restore...
  Restored /data/agent/_work/95/s/DataHunter-Main/domain/Datahunter.LCA.Model/Datahunter.LCA.Model.csproj (in 316 ms).
  Restored /data/agent/_work/95/s/DataHunter-Main/infrastructure/Datahunter.Azure/Datahunter.Azure.csproj (in 3.37 sec).
  Restored /data/agent/_work/95/s/DataHunter-Main/domain/Datahunter.Model/Datahunter.Model.csproj (in 2 ms).
  Restored /data/agent/_work/95/s/DataHunter-Main/domain/Datahunter.Metadata/Datahunter.Metadata.csproj (in 3.79 sec).
  Restored /data/agent/_work/95/s/DataHunter-Main/tests/Datahunter.Tests.Helpers/Datahunter.Tests.Helpers.csproj (in 3.81 sec).
  Restored /data/agent/_work/95/s/DataHunter-Main/infrastructure/Coordinator.Infrastructure/Coordinator.Infrastructure.csproj (in 3.86 sec).
  Restored /data/agent/_work/95/s/DataHunter-Main/persistence/Datahunter.Persistence/Datahunter.Persistence.csproj (in 3.83 sec).
  Restored /data/agent/_work/95/s/DataHunter-Main/yakedotnet/YakeRebuild/YakeRebuild.csproj (in 29 ms).
  Restored /data/agent/_work/95/s/DataHunter-Main/yakedotnet/SegTok/SegTok.csproj (in 19 ms).
  Restored /data/agent/_work/95/s/DataHunter-Main/tools/AdminToolsCLI/AdminToolsCLI.csproj (in 3.94 sec).
  Restored /data/agent/_work/95/s/DataHunter-Main/domain/Datahunter.Lexicon/Datahunter.Lexicon.csproj (in 203 ms).
  Restored /data/agent/_work/95/s/DataHunter-Main/application/PublicationDataCLI/PublicationDataCLI.csproj (in 4.14 sec).
  Restored /data/agent/_work/95/s/DataHunter-Main/application/Coordinator.Application/Coordinator.Application.csproj (in 307 ms).
  Restored /data/agent/_work/95/s/DataHunter-Main/ui/Datahunter.UI/Datahunter.UI.csproj (in 331 ms).
  Restored /data/agent/_work/95/s/DataHunter-Main/domain/Datahunter.Core/Datahunter.Core.csproj (in 491 ms).
  Restored /data/agent/_work/95/s/DataHunter-Main/application/AnalyzerCLI/AnalyzerCLI.csproj (in 4.4 sec).
  Restored /data/agent/_work/95/s/DataHunter-Main/ui/Datahunter.Metadata.Components/Datahunter.Metadata.Components.csproj (in 392 ms).
  Restored /data/agent/_work/95/s/DataHunter-Main/ui/Analyzer.UI/Analyzer.UI.csproj (in 424 ms).
  Restored /data/agent/_work/95/s/DataHunter-Main/tools/LexiconGenerator/LexiconGenerator.fsproj (in 344 ms).
  Restored /data/agent/_work/95/s/DataHunter-Main/ui/ReportViewer.UI/ReportViewer.UI.csproj (in 653 ms).
  Restored /data/agent/_work/95/s/DataHunter-Main/tests/ReportViewer.Shared.Tests/ReportViewer.Shared.Tests.csproj (in 442 ms).
  Restored /data/agent/_work/95/s/DataHunter-Main/tests/Datahunter.Tests/Datahunter.Tests.csproj (in 680 ms).
  ReqnrollFeatureFiles: AnalysisTests/Csv/CSVParsing.feature;AnalysisTests/Csv/FileCleanUpAfterAnalysis.feature;AnalysisTests/Csv/HeaderSelection.feature;AnalysisTests/Excel/Features/RecognizerRuntime.feature;AnalysisTests/Excel/Features/TableMetadata.feature;AnalysisTests/Excel/Features/UnformattedData.feature;AnalysisTests/FileAnalysis.feature;AnalysisTests/JsonConfig/JsonConfiguration.feature;AnalysisTests/PDF/PDFAnalysis.feature;AnalysisTests/SourceMetadata/SourceMetadataAnalysis.feature;AnalysisTests/UnsupportedFiles/UnsupportedFiles.feature;DocumentAI/DocumentAI.feature;FileContextTests/FileContext.feature;FilePreprocessorTests/FilePreprocessor.Feature;InvalidData/DQErrorCodes.feature;LCADetection/LCAFileDetection.feature;LCAExtractionTests/Brightway/BW2PackageExtraction.Feature;LCAExtractionTests/ILCD/ILCDExtraction.Feature;LCAExtractionTests/OpenLCA/OpenLCAExtraction.Feature;PublicationDataCLITests/CloudBlobPublication.feature;PublicationDataCLITests/ZenodoPublications.feature;RecognitionTests/ColumnDataTypeAnalysis1.feature;RecognitionTests/ColumnPIITypesAnalysis1.feature;RecognitionTests/DataRecognitionFeature.feature;RecognitionTests/MLDataRecognitionFeature.feature;RecognizerAssignmentTests/RecognizerAssignmentFileFeature.feature;RecognizerAssignmentTests/RecognizerNonNumericAssignmentSQLFeature.feature;RecognizerAssignmentTests/RecognizerNumericAssignmentSQLFeature.feature;RecognizerTests/Base/NumberRecognizer.Feature;ReportUITests/RiskLevels/TableRiskLevels.feature;ReportUITests/RiskLevels/TableSeverityCountAnalysis.feature;ToolsTests/NumberFormatter.Feature
/home/apptionadmin/.nuget/packages/reqnroll.tools.msbuild.generation/2.1.0/build/Reqnroll.Tools.MsBuild.Generation.targets(93,5): error MSB4018: The "GenerateFeatureFileCodeBehindTask" task failed unexpectedly. [/data/agent/_work/95/s/DataHunter-Main/tests/Datahunter.Tests/Datahunter.Tests.csproj]
/home/apptionadmin/.nuget/packages/reqnroll.tools.msbuild.generation/2.1.0/build/Reqnroll.Tools.MsBuild.Generation.targets(93,5): error MSB4018: Reqnroll.ReqnrollException: Unable to load plugin assembly: /home/apptionadmin/.nuget/packages/reqnroll.xunit/2.1.0/build/netstandard2.0/Reqnroll.xUnit.Generator.ReqnrollPlugin.dll. Please check https://go.reqnroll.net/doc-plugins for details. (Framework: .NET 8.0.5) [/data/agent/_work/95/s/DataHunter-Main/tests/Datahunter.Tests/Datahunter.Tests.csproj]
/home/apptionadmin/.nuget/packages/reqnroll.tools.msbuild.generation/2.1.0/build/Reqnroll.Tools.MsBuild.Generation.targets(93,5): error MSB4018:  ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Extensions.DependencyModel, Version=8.0.0.1, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified. [/data/agent/_work/95/s/DataHunter-Main/tests/Datahunter.Tests/Datahunter.Tests.csproj]
/home/apptionadmin/.nuget/packages/reqnroll.tools.msbuild.generation/2.1.0/build/Reqnroll.Tools.MsBuild.Generation.targets(93,5): error MSB4018:  [/data/agent/_work/95/s/DataHunter-Main/tests/Datahunter.Tests/Datahunter.Tests.csproj]
/home/apptionadmin/.nuget/packages/reqnroll.tools.msbuild.generation/2.1.0/build/Reqnroll.Tools.MsBuild.Generation.targets(93,5): error MSB4018: File name: 'Microsoft.Extensions.DependencyModel, Version=8.0.0.1, Culture=neutral, PublicKeyToken=adb9793829ddae60' [/data/agent/_work/95/s/DataHunter-Main/tests/Datahunter.Tests/Datahunter.Tests.csproj]

```

### Steps to Reproduce

n/a

**Comment by ajeckmans** [comment]
Are you referencing Microsoft.Extensions.DependencyModel directly in your project? It looks like it might have copied a different version than the one that ReqnRoll depends on 8.0.1 (or greater) and it cannot load the assembly anymore.

**Comment by gasparnagy** [comment]
@darren-zdc Do you have any feedback on this according to the hint of @ajeckmans?

**Comment by gasparnagy** [comment]
Closing this for now, if you have any feedback, please reopen.

**Comment by Alazrian** [comment]
Hello,
I just migrate from Specflow to reqnroll nugets with the latest version (2.2.1) and I have the same error as darren-zdc.
`##[error]/root/.nuget/packages/reqnroll.tools.msbuild.generation/2.2.1/build/Reqnroll.Tools.MsBuild.Generation.targets(93,5): Error MSB4018: The "GenerateFeatureFileCodeBehindTask" task failed unexpectedly.
Reqnroll.ReqnrollException: Unable to load plugin assembly: /root/.nuget/packages/reqnroll.xunit/2.2.1/build/netstandard2.0/Reqnroll.xUnit.Generator.ReqnrollPlugin.dll. Please check https://go.reqnroll.net/doc-plugins for details. (Framework: .NET 8.0.7)
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Extensions.DependencyModel, Version=8.0.0.2, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
`
I tried to add nuget package explicitly to Microsoft.Extensions.DependencyModel 8.0.0 but the error was still here. (nuget 8.0.0.2) does not exist, there is 8.0.0 or 8.0.1 or 8.0.2).
I downgraded reqnroll to version 2.0.3 as this one worked for darren-zdc, and it works for me too !

So I think there is really a problem superior versions. I use .NET 8.

**Comment by ryu1205** [comment]
Hi,

I've experiencing the same problem in the Azure yaml pipeline when attempting to use any version higher than 2.0.3. This is a dotnet 8 solution.

Failing Yaml task:
```
- task: DotNetCoreCLI@2
  displayName: 'Publish Automation Test project'
  inputs:
    command: 'publish'
    projects: '**/myProjectPath/**/*Tests.csproj'
    publishWebProjects: false
    arguments: '--configuration $(buildConfiguration)'
    outputDir: '$(build.artifactstagingdirectory)'
    zipAfterPublish: false
```

Errors:
`C:\Windows\ServiceProfiles\NetworkService\.nuget\packages\reqnroll.tools.msbuild.generation\2.4.0\build\Reqnroll.Tools.MsBuild.Generation.targets(93,5): error :    at Reqnroll.Generator.Plugins.GeneratorPluginLoader.LoadPlugin(PluginDescriptor pluginDescriptor) MyAutomationProject
C:\Windows\ServiceProfiles\NetworkService\.nuget\packages\reqnroll.tools.msbuild.generation\2.4.0\build\Reqnroll.Tools.MsBuild.Generation.targets(93,5): error : [Reqnroll] Reqnroll.ReqnrollException: Unable to load plugin assembly: C:\Windows\ServiceProfiles\NetworkService\.nuget\packages\reqnroll.nunit\2.4.0\build\\netstandard2.0\Reqnroll.NUnit.Generator.ReqnrollPlugin.dll. Please check https://go.reqnroll.net/doc-plugins for details. (Framework: .NET 8.0.0) MyAutomationProject
C:\Windows\ServiceProfiles\NetworkService\.nuget\packages\reqnroll.tools.msbuild.generation\2.4.0\build\Reqnroll.Tools.MsBuild.Generation.targets(93,5): error :  ---> System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Extensions.DependencyModel, Version=8.0.0.2, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Could not find or load a specific file. (0x80131621) MyAutomationProject
C:\Windows\ServiceProfiles\NetworkService\.nuget\packages\reqnroll.tools.msbuild.generation\2.4.0\build\Reqnroll.Tools.MsBuild.Generation.targets(93,5): error : File name: 'Microsoft.Extensions.DependencyModel, Version=8.0.0.2, Culture=neutral, PublicKeyToken=adb9793829ddae60' MyAutomationProject
C:\Windows\ServiceProfiles\NetworkService\.nuget\packages\reqnroll.tools.msbuild.generation\2.4.0\build\Reqnroll.Tools.MsBuild.Generation.targets(93,5): error :  ---> System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Extensions.DependencyModel, Version=8.0.0.2, Culture=neutral, PublicKeyToken=adb9793829ddae60'. MyAutomationProject
C:\Windows\ServiceProfiles\NetworkService\.nuget\packages\reqnroll.tools.msbuild.generation\2.4.0\build\Reqnroll.Tools.MsBuild.Generation.targets(93,5): error :    at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath) MyAutomationProject
C:\Windows\ServiceProfiles\NetworkService\.nuget\packages\reqnroll.tools.msbuild.generation\2.4.0\build\Reqnroll.Tools.MsBuild.Generation.targets(93,5): error :    at Microsoft.Build.Shared.CoreClrAssemblyLoader.LoadAndCache(AssemblyLoadContext context, String fullPath) MyAutomationProject
C:\Windows\ServiceProfiles\NetworkService\.nuget\packages\reqnroll.tools.msbuild.generation\2.4.0\build\Reqnroll.Tools.MsBuild.Generation.targets(93,5): error :    at Microsoft.Build.Shared.CoreClrAssemblyLoader.TryResolveAssemblyFromPaths(AssemblyLoadContext context, AssemblyName assemblyName, IEnumerable`1 searchPaths) MyAutomationProject
C:\Windows\ServiceProfiles\NetworkService\.nuget\packages\reqnroll.tools.msbuild.generation\2.4.0\build\Reqnroll.Tools.MsBuild.Generation.targets(93,5): error :    at Microsoft.Build.Shared.CoreClrAssemblyLoader.TryResolveAssembly(AssemblyLoadContext context, AssemblyName assemblyName) MyAutomationProject
C:\Windows\ServiceProfiles\NetworkService\.nuget\packages\reqnroll.tools.msbuild.generation\2.4.0\build\Reqnroll.Tools.MsBuild.Generation.targets(93,5): error :    at System.Runtime.Loader.AssemblyLoadContext.GetFirstResolvedAssemblyFromResolvingEvent(AssemblyName assemblyName) MyAutomationProject
C:\Windows\ServiceProfiles\NetworkService\.nuget\packages\reqnroll.tools.msbuild.generation\2.4.0\build\Reqnroll.Tools.MsBuild.Generation.targets(93,5): error :    at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName) MyAutomationProject
C:\Windows\ServiceProfiles\NetworkService\.nuget\packages\reqnroll.tools.msbuild.generation\2.4.0\build\Reqnroll.Tools.MsBuild.Generation.targets(93,5): error :    at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingResolvingEvent(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName) MyAutomationProject
C:\Windows\ServiceProfiles\NetworkService\.nuget\packages\reqnroll.tools.msbuild.generation\2.4.0\build\Reqnroll.Tools.MsBuild.Generation.targets(93,5): error :    at Reqnroll.Plugins.AssemblyResolverBase.SetupDependencyContext(String path, Assembly assembly, Boolean throwOnError) MyAutomationProject
C:\Windows\ServiceProfiles\NetworkService\.nuget\packages\reqnroll.tools.msbuild.generation\2.4.0\build\Reqnroll.Tools.MsBuild.Generation.targets(93,5): error :    at Reqnroll.Plugins.DotNetCorePluginAssemblyResolver.Initialize(String path) MyAutomationProject
C:\Windows\ServiceProfiles\NetworkService\.nuget\packages\reqnroll.tools.msbuild.generation\2.4.0\build\Reqnroll.Tools.MsBuild.Generation.targets(93,5): error :    at Reqnroll.Plugins.AssemblyResolverBase.<>c__DisplayClass4_0.<.ctor>b__0() MyAutomationProject
C:\Windows\ServiceProfiles\NetworkService\.nuget\packages\reqnroll.tools.msbuild.generation\2.4.0\build\Reqnroll.Tools.MsBuild.Generation.targets(93,5): error :    at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode) MyAutomationProject
C:\Windows\ServiceProfiles\NetworkService\.nuget\packages\reqnroll.tools.msbuild.generation\2.4.0\build\Reqnroll.Tools.MsBuild.Generation.targets(93,5): error :    at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor) MyAutomationProject
C:\Windows\ServiceProfiles\NetworkService\.nuget\packages\reqnroll.tools.msbuild.generation\2.4.0\build\Reqnroll.Tools.MsBuild.Generation.targets(93,5): error :    at System.Lazy`1.CreateValue() MyAutomationProject
C:\Windows\ServiceProfiles\NetworkService\.nuget\packages\reqnroll.tools.msbuild.generation\2.4.0\build\Reqnroll.Tools.MsBuild.Generation.targets(93,5): error :    at Reqnroll.Plugins.AssemblyResolverBase.GetAssembly() MyAutomationProject
C:\Windows\ServiceProfiles\NetworkService\.nuget\packages\reqnroll.tools.msbuild.generation\2.4.0\build\Reqnroll.Tools.MsBuild.Generation.targets(93,5): error :    at Reqnroll.Plugins.DotNetCorePluginAssemblyResolver.Load(String path) MyAutomationProject
C:\Windows\ServiceProfiles\NetworkService\.nuget\packages\reqnroll.tools.msbuild.generation\2.4.0\build\Reqnroll.Tools.MsBuild.Generation.targets(93,5): error :    at Reqnroll.Plugins.DotNetCorePluginAssemblyLoader.LoadAssembly(String assemblyPath) MyAutomationProject
C:\Windows\ServiceProfiles\NetworkService\.nuget\packages\reqnroll.tools.msbuild.generation\2.4.0\build\Reqnroll.Tools.MsBuild.Generation.targets(93,5): error :    at Reqnroll.Generator.Plugins.GeneratorPluginLoader.LoadPlugin(PluginDescriptor pluginDescriptor) MyAutomationProject
C:\Windows\ServiceProfiles\NetworkService\.nuget\packages\reqnroll.tools.msbuild.generation\2.4.0\build\Reqnroll.Tools.MsBuild.Generation.targets(93,5): error :    --- End of inner exception stack trace --- MyAutomationProject
C:\Windows\ServiceProfiles\NetworkService\.nuget\packages\reqnroll.tools.msbuild.generation\2.4.0\build\Reqnroll.Tools.MsBuild.Generation.targets(93,5): error :    at Reqnroll.Generator.Plugins.GeneratorPluginLoader.LoadPlugin(PluginDescriptor pluginDescriptor) MyAutomationProject
C:\Windows\ServiceProfiles\NetworkService\.nuget\packages\reqnroll.tools.msbuild.generation\2.4.0\build\Reqnroll.Tools.MsBuild.Generation.targets(93,5): error :    at Reqnroll.Generator.GeneratorContainerBuilder.LoadPlugin(PluginDescriptor pluginDescriptor, IGeneratorPluginLoader pluginLoader, GeneratorPluginEvents generatorPluginEvents, UnitTestProviderConfiguration unitTestProviderConfiguration) MyAutomationProject
C:\Windows\ServiceProfiles\NetworkService\.nuget\packages\reqnroll.tools.msbuild.generation\2.4.0\build\Reqnroll.Tools.MsBuild.Generation.targets(93,5): error :    at Reqnroll.Generator.GeneratorContainerBuilder.LoadPlugins(ObjectContainer container, GeneratorPluginEvents generatorPluginEvents, UnitTestProviderConfiguration unitTestProviderConfiguration, IEnumerable`1 generatorPlugins) MyAutomationProject
C:\Windows\ServiceProfiles\NetworkService\.nuget\packages\reqnroll.tools.msbuild.generation\2.4.0\build\Reqnroll.Tools.MsBuild.Generation.targets(93,5): error :    at Reqnroll.Generator.GeneratorContainerBuilder.CreateContainer(ReqnrollConfigurationHolder configurationHolder, ProjectSettings projectSettings, IEnumerable`1 generatorPluginInfos, IObjectContainer parentObjectContainer) MyAutomationProject
C:\Windows\ServiceProfiles\NetworkService\.nuget\packages\reqnroll.tools.msbuild.generation\2.4.0\build\Reqnroll.Tools.MsBuild.Generation.targets(93,5): error :    at Reqnroll.Tools.MsBuild.Generation.WrappedGeneratorContainerBuilder.BuildGeneratorContainer(ReqnrollConfigurationHolder reqnrollConfigurationHolder, ProjectSettings projectSettings, IReadOnlyCollection`1 generatorPluginInfos, IObjectContainer rootObjectContainer) MyAutomationProject
C:\Windows\ServiceProfiles\NetworkService\.nuget\packages\reqnroll.tools.msbuild.generation\2.4.0\build\Reqnroll.Tools.MsBuild.Generation.targets(93,5): error :    at Reqnroll.Tools.MsBuild.Generation.GenerateFeatureFileCodeBehindTaskExecutor.Execute() MyAutomationProject

##[error]Error: The process 'D:\Agents\01\_work\_tool\dotnet\dotnet.exe' failed with exit code 1
`

It would be appreciated if anyone could provide any assistance.

Regards

**Comment by sudgarre** [comment]
@ryu1205 I was able to solve the above by adding below package, Reqnroll versions are at 2.3.0 & all other Microsoft.Extensions.* dependencies are at 9.0.4. Please give a try from your end

<PackageReference Include="Microsoft.Extensions.DependencyModel" Version="9.0.4" />
