### ISSUE TITLE
VisualStudio2022 Plugin not working

### ISSUE THREAD

**Issue by alahane-techtel** [reqnroll/Reqnroll#260]
### Reqnroll Version

v2.1.0

### Which test runner are you using?

xUnit

### Test Runner Version Number

2.6.6

### .NET Implementation

.NET 8.0

### Test Execution Method

Visual Studio Test Explorer

### Content of reqnroll.json configuration file

{
    "$schema": "https://schemas.reqnroll.net/reqnroll-config-latest.json",
    
    "bindingAssemblies": [
    ]
}

### Issue Description

Was just trying Reqnroll for the first time. Using latest of all as of today. However, after doing all the steps as per the instructions, the context menus are not working. I cannot navigate to step defs either. The options menu also doesn't show any Reqnroll options.

However, I'll like to emphasise that the tests run fine.

--------------------------------------------------------------------------------
![image](https://github.com/user-attachments/assets/7f295a5c-7f26-464d-a55f-62509f7255c5)
--------------------------------------------------------------------------------
![image](https://github.com/user-attachments/assets/71722c15-6b0d-4ca3-8e40-6d345230e7d6)
--------------------------------------------------------------------------------
![image](https://github.com/user-attachments/assets/9dc8daa9-9487-4667-bcb2-ee2947e4906b)
--------------------------------------------------------------------------------
![image](https://github.com/user-attachments/assets/4494adc3-3c38-4b97-86a7-d493948f4f5a)

### Steps to Reproduce

use latest VisualStudio 2022.

Install the plugin by following:
https://docs.reqnroll.net/latest/installation/setup-ide.html#setup-vs

After doing this, I was not able to see the project template for Reqnroll. Then I installed the project templates using this:

`dotnet new install Reqnroll.Templates.DotNet`

Then templates started working. But now the context menus, step def nav and options menu not working, as explained above. 

However, I'll like to emphasise that the tests run fine.

**Comment by UL-ChrisGlew** [comment]
Would it be possible to raise this issue in the below repository, as it relates to the Visual Studio 2022 extension:

[[Reqnroll.VisualStudio](https://github.com/reqnroll/Reqnroll.VisualStudio)](https://github.com/reqnroll/Reqnroll.VisualStudio)

**Comment by UL-ChrisGlew** [comment]
Should now be tracking this issue here:

https://github.com/reqnroll/Reqnroll.VisualStudio/issues/37

**Comment by alahane-techtel** [comment]
thanks @UL-ChrisGlew.

**Comment by alahane-techtel** [comment]
amazing. I just tried it. All works absolutely fine now :) Thanks again @UL-ChrisGlew 
You guys are doing afantastic job. Cant tell you how much relieved I'm by seeing this support. I was scared today, when after a couple of years since using Specflow last time, today when I saw it dead, I was like freaked out. Now I'm confident :)

**Comment by gasparnagy** [comment]
A hotfix has been published to the marketplace as v2024.4.154.

I will keep this issue open for a day so that people can find it.
