### ISSUE TITLE
Issue with "BeforeTestRun" & "AfterTestRun" hooks

### ISSUE THREAD

**Issue by d4v1dk0n7** [reqnroll/Reqnroll#269]
### Reqnroll Version

2.1.0

### Which test runner are you using?

NUnit

### Test Runner Version Number

4.2.2

### .NET Implementation

.NET 8.0

### Test Execution Method

Visual Studio Test Explorer

### Content of reqnroll.json configuration file

{
  "$schema": "https://schemas.reqnroll.net/reqnroll-config-latest.json",
  "language": {
    "feature": "en-US",
    "binding": "en-US"
  },
  "generator": {
    "allowDebugGeneratedFiles": false,
    "allowRowTests": true,
    "addNonParallelizableMarkerForTags": [ "nonparallelizable" ]
  },
  "runtime": {
    "missingOrPendingStepsOutcome": "Pending",
    "obsoleteBehavior": "Warn",
    "stopAtFirstError": true
  },
  "trace": {
    "stepDefinitionSkeletonStyle": "CucumberExpressionAttribute",
    "coloredOutput": true
  },
  "bindingAssemblies": [
    {
      "assembly": "QA.TestCore"
    }
  ]
}

### Issue Description

Hi team,

I've noticed that the hooks "**BeforeTestRun**" and "**AfterTestRun**" are not being called when it should, all the other hooks I'm using are working fine (BeforeFeature, AfterFeature, BeforeScenario, AfterScenario, BeforeStep, AfterStep)...
I'm calling these hooks this way, I think it's correct:

        [BeforeTestRun]
        public static void BeforeTestRun()
        {
            System.Console.WriteLine("BeforeTestRun test");
        }

I'm using the latest reqnroll version 2.1.0...
Any help will be appreciated...

Thanks!

### Steps to Reproduce

Just include the hooks ""BeforeTestRun" and "AfterTestRun" in the Hooks class and try to make them work...

**Comment by clrudolphi** [comment]
I've created a new project using NUnit and .NET 8. I cannot recreate your problem.
Have you tried Debugging your project/sample with a breakpoint within your BeforeTestRun method?

**Comment by d4v1dk0n7** [comment]
hi @clrudolphi,

Yes, I've tried with a breakpoint in the method... When I execute It's not accesing the code inside...

**Comment by clrudolphi** [comment]
Can you share your project? Easiest way would be to host it on your github account and point us to it.

**Comment by d4v1dk0n7** [comment]
Hi @clrudolphi,

This is an appium + reqnroll project to execute tests in mobile devices, sorry but in this case I can't share the project...
I don't know why it's happening this, all the dependencies are updated to the latest versions, all seems to be fine...

**Comment by d4v1dk0n7** [comment]
Hi @clrudolphi,

I've recreated the specflow project and now it's working.. But I don't understand why...
Anyway.. Thanks for your help in pointing me in the right direction :)

**Comment by gasparnagy** [comment]
Just for the record I would like to highlight, that `Console.WriteLine` typically does not work in Before/AfterTestRun hooks. Having a breakpoint and debug, or writing a line to a log file is a better way to diagnose these things.

Closing the issue for now.
