### ISSUE TITLE
Both VS related pages in "IDE integrations" section are named the same

### ISSUE THREAD

**Issue by gucu112** [reqnroll/Reqnroll#278]
### Related Documentation Page

https://docs.reqnroll.net/latest/ide-integrations/index.html

### Type of the problem

Typo, language or grammar error

### Problem Description

Hey Guys,

In section "Integrations > IDE integrations" both pages are named the same:
![screenshot](https://github.com/user-attachments/assets/6d46f08f-2e3a-49b0-9393-f1e208f96e63)

However, one is related to Visual Studio and another to Visual Studio Code. Probably it would be a good idea to include "Code" suffix on 2nd page:
https://github.com/reqnroll/Reqnroll/blob/main/docs/ide-integrations/vscode/index.md

I hope it helps and keep up the good work!

Cheers,
Bart

**Comment by melchiork** [comment]
I've created a super-small PR to fix this: #280
