### ISSUE TITLE
Reqnroll.Microsoft.Extensions.DependencyInjection : not possible to get a IReqnrollOutputHelper in the [ScenarioDependencies]

### ISSUE THREAD

**Issue by StefH** [reqnroll/Reqnroll#317]
### Reqnroll Version

2.1.1

### Which test runner are you using?

xUnit

### Test Runner Version Number

xunit.runner.visualstudio 2.8.2

### .NET Implementation

.NET 8.0

### Test Execution Method

Visual Studio Test Explorer

### Issue Description

I want to access the IReqnrollOutputHelper in the [ScenarioDependencies] method in order to register my custom ILogger implementation.

### Steps to Reproduce

I followed this https://github.com/reqnroll/Reqnroll/issues/247

When I try this code:
``` C#
public static bool wasExecuted = false;
[BeforeScenario]
public static void ConfigureServices(ITestRunContext testRunContext, ITestThreadContext testThreadContext)
{
  if (wasExecuted) return;
  wasExecuted = true;

  var globalContainer = testRunContext.TestRunContainer; // this is the real global container used by all parallel threads
  var testThreadContainer = testThreadContext.TestThreadContainer; // this is what you have used in your hook
  //do service regs
}
```

I get error like:
`System.InvalidOperationException : No service for type 'Reqnroll.ITestThreadContext' has been registered.`

---

When I use this code:
``` csharp
[Binding]
public class Startup
{
    private static IReqnrollOutputHelper? _outputHelper;

    protected Startup()
    {
    }

    [BeforeScenario]
    public static void Before(TestThreadContext testThreadContext)
    {
        if (_outputHelper != null)
        {
            return;
        }

        _outputHelper = testThreadContext.TestThreadContainer.Resolve<IReqnrollOutputHelper>();
    }

    [ScenarioDependencies]
    public static IServiceCollection CreateServices()
    {
        return new ServiceCollection()
            .AddLogging(builder => builder
                .AddProvider(new ReqnrollLoggerProvider(_outputHelper!)))
            .AddTransient<Calculator>();
    }
}
```

When using `BeforeFeature` or `BeforeScenario`, the CreateServices is called first, after that the Before method is called, so that does not work.

If I use `BeforeTestRun`, I get error:
```
System.Collections.Generic.KeyNotFoundException : The given key 'Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope' was not present in the dictionary.
```

The only code which does work is like:
``` c#
[BeforeTestRun]
public static void BeforeTestRun(ITestRunnerManager testRunnerManager)
{
    if (_outputHelper != null)
    {
        return;
    }

    var runner = testRunnerManager.GetTestRunner();
    var context = runner.TestThreadContext;
    _outputHelper = context.TestThreadContainer.Resolve<IReqnrollOutputHelper>();
    testRunnerManager.ReleaseTestThreadContext(context);
}
```

Although I'm not sure this is the correct solution....

### Link to Repro Project

https://github.com/StefH/Stef.Extensions.SpecFlow.Logging/pull/1

**Comment by gasparnagy** [comment]
See the comment relevant for this issue from #247 here: https://github.com/reqnroll/Reqnroll/issues/247#issuecomment-2460401450

Also important to note that the workaround provided above will only work for non-parallel execution.

**Comment by gasparnagy** [comment]
Closing this ticket, but please reopen if there is anything new on it
