### ISSUE TITLE
Can't find links to make living documentation

### ISSUE THREAD

**Issue by JakeTheCorn** [reqnroll/Reqnroll#329]
### Type of the problem

Missing information

### Problem Description

Hey all,

First up, I'm a big fan of the bdd books and of your work in general. 

I'm having a bit of trouble finding documentation in reqnroll similar to other bdd tools with living documentation.

Is there a way to produce living docs in reqnroll similar to specflow?

https://docs.specflow.org/projects/specflow/en/latest/Tools/Reporting.html

**Comment by gasparnagy** [comment]
Added an attention note to https://docs.reqnroll.net/latest/guides/migrating-from-specflow.html

**Comment by gasparnagy** [comment]
The living doc support is tracked here: https://github.com/orgs/reqnroll/discussions/196
