### ISSUE TITLE
Tags on Examples are not passed to scenario as TestCategoryAttribute

### ISSUE THREAD

**Issue by TacoVerhagen** [reqnroll/Reqnroll#342]
### Reqnroll Version

2.2.1

### Which test runner are you using?

MSTest

### Test Runner Version Number

3.6.3

### .NET Implementation

.NET 8.0

### Test Execution Method

Visual Studio Test Explorer

### Content of reqnroll.json configuration file

{
  "$schema": "https://schemas.reqnroll.net/reqnroll-config-latest.json",

  "language": {
    "feature": "en-us",
    "binding": "en-us"
  }
}

### Issue Description

See repo steps
The tag @Example1 is _not_ passed to the scenario as a TestCategoryAttribute. In Reqnroll version 1.0.0 and the latest Specflow version this was the case.

ScenarioContext.ScenarioInfo.Tags gives the correct answer: ScenarioTag && Example1

### Steps to Reproduce

@FeatureTage
Feature: TagSample
A short summary of the feature

@ScenarioTag
Scenario: Sample Scenario
    Scenario summary text
    Given sample step

@Example1
Examples:
    | sample |
    | nr1    |

### Reqnroll version 1.x generates the .feature.cs with:
[Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
[Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Sample Scenario: nr1")]
[Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "TagSample")]
[Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("FeatureTage")]
[Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("ScenarioTag")]
**[Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Example1")]**
[Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "nr1")]
[Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:sample", "nr1")]
public async System.Threading.Tasks.Task SampleScenario_Nr1()

### Reqnroll version >=2.x generates:
[Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
[Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Sample Scenario")]
[Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "TagSample")]
[Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("FeatureTage")]
[Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("ScenarioTag")]
[Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("nr1", "", new string[] {
        "Example1"})]
public async System.Threading.Tasks.Task SampleScenario(string sample, string notUsed6248, string[] exampleTags)

**Comment by obligaron** [comment]
This happens since version 2.0 as this is the first version that includes #54.
#54 uses `DataRowAttribute` for gherkin examples.

Sadly MsTest `DataRowAttribute` doesn't support custom `TestCategory` per `DataRow`. See also https://github.com/microsoft/testfx/issues/4089 and https://github.com/microsoft/testfx/issues/1043#issuecomment-1942279024.

**Comment by clrudolphi** [comment]
You can use a reqnroll.json configuration file to force the generation of a test method per example row; and when doing so the Examples tag will be generated as a TestCategory for that method.

reqnroll.json:
```javascript
{
  "$schema": "https://schemas.reqnroll.net/reqnroll-config-latest.json",
  "generator": {"allowRowTests" :  false},

  "bindingAssemblies": [
  ]
}
``` 

Resulting code-behind generation:

```c#
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Sample Scenario: nr1")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "342")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("FeatureTag")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("ScenarioTag")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Example1")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "nr1")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:sample", "nr1")]
        public async System.Threading.Tasks.Task SampleScenario_Nr1()
        {
...
        }
    }

```

**Comment by TacoVerhagen** [comment]
@obligaron, clear answer. The real issue is upstream with MSTest.
I could dive into the code and make a workaround in the generator, technically anything is possible. How desirable is this, as Microsoft has it on its backlog _somewhere_?

@clrudolphi Thank you! That solves the issue for now!
May I suggest adding this to the documentation somewhere? I couldn't find this known issue or workaround (yes, I can write a PR myself)

**Comment by gasparnagy** [comment]
MsTest backlog: maybe here? https://github.com/microsoft/testfx

@TacoVerhagen I don't think this is mentioned in the docs, yes, please send a PR for the doc change. 🙏
