### ISSUE TITLE
Does `addNonParallelizableMarkerForTags` work for MsTest?

### ISSUE THREAD

**Issue by DrEsteban** [reqnroll/Reqnroll#346]
### Related Documentation Page

https://docs.reqnroll.net/latest/execution/parallel-execution.html#excluding-reqnroll-features-from-parallel-execution

### Type of the problem

Missing information

### Problem Description

The [documentation](https://github.com/reqnroll/Reqnroll/blob/4642769a5a2ec908eaf09401aef63a28bd3481d9/docs/execution/parallel-execution.md?plain=1#L103-L112) explains how the generator makes this option work for xUnit, but not the other test frameworks.

The reason I ask: When I configure this setting in my project, I see no difference in the generated `*.feature.cs` file for a scenario that has one of the tags I specify. (In case it matters, I have method-level parallelism configured for MsTest in my AssemblyInfo.cs)

So I'm wondering if this option actually does anything in MsTest? If so, it might be nice to include a little blurb for how it works. Same thing for NUnit.

Thanks!

**Comment by obligaron** [comment]
It should work with MsTest and NUnit. At least we have tests in CI for it. 😉 

Did you specify the same `@Tag` in the .feature file and the configuration?
Only if both match the `Microsoft.VisualStudio.TestTools.UnitTesting.DoNotParallelizeAttribute` is set.

Hope this helps a bit.
