### ISSUE TITLE
Reqnroll 2.21 GeneratorPlugin - GenerateFeatureFileCodeBehindTask task failed unexpectedly

### ISSUE THREAD

**Issue by renegadexx** [reqnroll/Reqnroll#353]
### Reqnroll Version

2.2.1

### Which test runner are you using?

NUnit

### Test Runner Version Number

4.6.0

### .NET Implementation

.NET 8.0

### Test Execution Method

Other – PLEASE SPECIFY

### Content of reqnroll.json configuration file

{
  "nunitRetry": {
    "enabled": true,
    "tryCount": 2
  }
}

### Issue Description

The databinding.Reqnroll.NUnit.Retry package is a GeneratorPlugin that is implemented with the ITestMethodDecorator interface to add the RetryAttribute for NUnit to each scenario. With the update from Reqnroll 2.1.1 to 2.2.2 the plugin no longer works. It no longer finds the reference to NUnit.

How can this issue be solved?

### Steps to Reproduce

- Open the solution with Reqnroll version 2.1.1
- Update the references to 2.2.1
- Update the GeneratorPlugin package to 5.9.0 which conatins Verson 2.2.1 of Reqnroll.CustomPlugin

Current result
The "GenerateFeatureFileCodeBehindTask" task failed unexpectedly.
System.IO.FileNotFoundException->Microsoft.Build.Framework
.BuildException.GenericBuildTransferredException: Could not load file or assembly 
'nunit.framework, Version=3.13.1.0, Culture=neutral, 
PublicKeyToken=2638cd05610744eb' or one of its dependencies. 

Expected result
- Retry attribute will be in the code behind file again

### Link to Repro Project

https://github.com/databinding-gmbh/ReqnrollGenericBuildTransferredException/tree/main/src

**Comment by olegKoshmeliuk** [comment]
@renegadexx  looks like an issue in databinding.Reqnroll.NUnit.Retry 5.9.0. 
For generator plugin, it's not mandatory to reference to nunit framework. 
Try to remove RetrySteps.cs from compilation to `databinding.Reqnroll.NUnit.Retry.ReqnrollPlugin` (use it only as content). and get rid of nunit reference in plugin assembly.

**Comment by olegKoshmeliuk** [comment]
@renegadexx  When you updated in from 2.1 to 2.2 there was change in NUnitAssemblyHooks template. 
It was updated to a static class. I think that's cause msbuild to load nunit.framework assembly. 
But as I mentioned before for generator plugin it's not required to reference NUnit from ReqnrollPlugin assembly. 

see commit diff:https://github.com/reqnroll/Reqnroll/commit/a52d7c7ef99acb446cb6c9b44b5bc127c8cbe7c4#diff-f70d8550dda7ed8576e771008ce148643216f0a97f7149364595764f9a5bda64R13

**Comment by renegadexx** [comment]
Thanks @olegKoshmeliuk for the hint, after the adjustment the error was fixed

**Comment by gasparnagy** [comment]
For the record, the NUnitAssemblyHooks should not be compiled with the generator assembly. The fact that it is compiled is probably caused by a wrong reference in the generator project: it should only have a reference to the `Reqnroll.CustomPlugin` package and not the `Reqnroll.NUnit` package.
