### ISSUE TITLE
Support DataRow/ScenarioOutlines in mstest v2 adapter

### ISSUE THREAD

**Issue by livioc** [reqnroll/Reqnroll#47]
Thx!

@livioc Would you be interested to also implement the [`[DataRow]`](https://learn.microsoft.com/en-us/visualstudio/test/how-to-create-a-data-driven-unit-test?view=vs-2022) attribute support as well? For xUnit and NUnit, SpecFlow (by default) generates a single parametrized test for scenario outlines and adds the examples as data rows. But for MsTest this was not implemented yet. (We should always keep the option to generate multiple methods, like we do for NUnit & xUnit.)

_Originally posted by @gasparnagy in https://github.com/reqnroll/Reqnroll/issues/42#issuecomment-1953765205_

**Comment by gasparnagy** [comment]
Thx! Looking forward to the PR. 

Structure side note: we try to keep the "issues" only for issues, so the feature requests should be tracked in the "Ideas" discussion topic (https://github.com/orgs/reqnroll/discussions/categories/ideas). I migrated this ticket to https://github.com/orgs/reqnroll/discussions/48 and closing it here.

The process is not fully established yet, and I'm not fully happy with it, but let's run it for a while to see how it works. Also see the related meta-discussion: https://github.com/orgs/reqnroll/discussions/26
