### ISSUE TITLE
Reqnroll is still using the file specflow.json

### ISSUE THREAD

**Issue by maoso** [reqnroll/Reqnroll#55]
### Reqnroll Version

1.0.1

### Which test runner are you using?

NUnit

### Test Runner Version Number

4.5.0

### .NET Implementation

.NET 6.0

### Test Execution Method

Visual Studio Test Explorer

### Issue Description

I am testing Reqnroll migration and when running it on Visual Studio 2022 I can see into the ReqnRoll output that still makes reference to specflow.json file. 

So it calls to the command dotnet.exe exec  < path to reqnroll-vs.dll > discovery < dll path > < path to **specflow.json** >

I think it shouldn't make reference to specflow.json probably should be reqnroll.json 

### Steps to Reproduce

I am testing Reqnroll migration and when running it on Visual Studio 2022 I can see into the ReqnRoll output that still makes reference to specflow.json file. 

So it calls to the command dotnet.exe exec  < path to reqnroll-vs.dll > discovery < dll path > < path to **specflow.json** >

I think it shouldn't make reference to specflow.json probably should be reqnroll.json

**Comment by gasparnagy** [comment]
Yes, as @konarx said it is by design for now. I'm closing the issue, but if you see anything with this approach that causes a problem, please reopen.
