### ISSUE TITLE
Issues with Cucumber Expressions

### ISSUE THREAD

**Issue by konarx** [reqnroll/Reqnroll#63]
### Reqnroll Version

1.0.1

### Which test runner are you using?

NUnit

### Test Runner Version Number

4.5.0

### .NET Implementation

.NET 6.0

### Test Execution Method

ReSharper Test Runner

### Content of reqnroll.json configuration file

```json
{
  "$schema": "https://schemas.reqnroll.net/reqnroll-config-latest.json",
  "bindingAssemblies": [
    {
      "assembly": "My.External.NuGet"
    }
  ]
}
```

### Issue Description

I am using Rider with the [latest build](https://github.com/reqnroll/Reqnroll.Rider/actions/runs/7951275864) of the Rider.Reqnroll plugin.
In a pretty easy Scenario:
```gherkin
@login
Scenario: Invalid login to My App
    When the user fills credentials as, username: my_user and password: 123pass456
    And clicks Login
    Then the user is not successfully logged in My App
```
I have a [Step Definition](https://docs.reqnroll.net/latest/automation/step-definitions.html#step-definitions), based on [Cucumber Expressions](https://docs.reqnroll.net/latest/automation/cucumber-expressions.html#cucumber-expressions):
```csharp
[When("the user fills credentials as, username: {word} and password: {word}")]
public async Task WhenTheUserFillsCredentialsAsUsernameAndPassword(string username, string password)
{
     _scenarioContext["currentUser"] = username;
     await _loginPage.FillCredentials(username, password);
}
```
This causes two issues:

1. The execution marks the test as Inconclusive and gives me the following log:
   > When the user fills credentials as, username: my_user and password: 123pass456
   -> No matching step definition found for the step. Use the following code to create one:
        [When(@"the user fills credentials as, username: my_user and password: (.*)pass(.*)")]
        public void WhenTheUserFillsCredentialsAsUsernameMy_UserAndPasswordPass(int p0, int p1)
        {
            _scenarioContext.Pending();
        }

   It seems like it does not support Cucumber Expressions. Is that a known issue? Do I do something wrong?

2. While the other Step Definitions are ok (they are not using Cucumber Expressions but Regex), all the other Steps within the same `.feature` file marked as "Cannot find a matching step definition", but the runner identifies them and run the tests successfully! Strange, uh?
![image](https://github.com/reqnroll/Reqnroll/assets/23631145/7692aba8-672b-4886-80d8-80011fc09d32)

### Steps to Reproduce

Implement the above Scenario

**Comment by gasparnagy** [comment]
@konarx could you please move this issue to the Reqroll.Rider project. I think it does not yet support cucumber expresssions.

**Comment by konarx** [comment]
Sure, I'll be happy to, but maybe the Documentation should state that it does not support Cucumber Expressions yet, just to avoid misunderstandings like this one.
